### ISSUE TITLE
tooltip_div blocks mouse events from underlying nodes when faded out by opacity

### ISSUE THREAD

**Issue by unverbuggt** [BenPortner/js_family_tree#15]
The tooltip_div is faded in by a `mouseover` event and faded out by `mouseout` on a node or its text. I've noticed that while the div is hidden by setting `opacity:0` it still blocks mouse events from happening on nodes it previously covered. Only by setting `visibility:hidden` the div will stop blocking mouse events on underlying nodes.
I've made too much specific changes in my fork to be able to create a pull request (Also I'm not too much of a git expert). But here are the changes I made to circumvent this: https://github.com/unverbuggt/mkdocs-familytree-example/commit/ea56f2e3f74984094f845d7f44705829480ea82b

**Comment by BenPortner** [comment]
Thanks a lot @unverbuggt! Should be fixed with https://github.com/BenPortner/js_family_tree/commit/211d1a4de08ebb6f53f976ab9a3c4e28583e019d. Feel free to re-open, if it isn't.
